<h1>Flights</h1>
<br /><br />

<table>
    <tr>
        <td>
            <u>from</u>
        </td>
        <td>
            <u>to</u>
        </td>
        <td>
            <u>distance</u>
        </td>
    </tr>  
    {flights}
    <tr>
        <td>
            <b>{from}</b>
        </td>
        <td>
            <b>{to}</b>
        </td>
        <td>
            <b>{distance}</b>
        </td>
    </tr>
    {/flights}
</table>
